package com.pensasha.backend.modules.user;

public enum Permissions {
    
        // PROPERTY
    PROPERTY_CREATE,
    PROPERTY_VIEW,
    PROPERTY_UPDATE,
    PROPERTY_DELETE,

    // TENANT
    TENANT_VIEW,
    TENANT_APPROVE,

    // RENT
    RENT_PAY,
    RENT_VIEW,
    RENT_CONFIRM_PAYMENT,

    // MAINTENANCE
    MAINTENANCE_CREATE,
    MAINTENANCE_VIEW,
    MAINTENANCE_ASSIGN,
    MAINTENANCE_RESOLVE,

    // DOCUMENTS
    DOCUMENT_VIEW,
    DOCUMENT_UPLOAD,

    // MESSAGES
    MESSAGE_SEND,
    MESSAGE_VIEW,

    // ANNOUNCEMENTS
    ANNOUNCEMENT_VIEW,
    ANNOUNCEMENT_CREATE,

    // REPORTS
    REPORT_VIEW,

    // ADMIN
    USER_VIEW,
    ROLE_VIEW,
    SYSTEM_SETTINGS_UPDATE

}
